### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by tenSunFree** [AdityaAnand1/Morphing-Material-Dialogs#3]
Use the environment
![2017-08-20_195400](https://user-images.githubusercontent.com/23090085/29494659-c9bafd5a-85e1-11e7-98ac-34eb3e693c60.jpg)

Problem
![02](https://user-images.githubusercontent.com/23090085/29494664-d4058a14-85e1-11e7-9016-c1a98a0ede09.jpg)
![03](https://user-images.githubusercontent.com/23090085/29494691-572dfcd2-85e2-11e7-9d01-c9774301052a.jpg)

How can i solve this problem?

**Comment by Aditya94A** [comment]
Thank you so much for including screenshots. I'm on the same AS version myself. I've updated the library to use 0.9.4.7 (latest) version of material dialogs. 0.9.4.6's support for support libs 26.0.1 was a little iffy.

It should resolve now. Please `git pull` and try again. If it still doesn't work, can you confirm that you can use material dialogs in another project? Because it's really just a plain dependency in jCenter, no other reason it shouldn't resolve.

**Comment by tenSunFree** [comment]
The problem is solved, thank you
